"""add rejected expense status

Revision ID: 605e88e01a0b
Revises: bd698cc5de7d
Create Date: 2026-08-22 10:58:04.375640

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "605e88e01a0b"
down_revision: str | Sequence[str] | None = "bd698cc5de7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE expense_status ADD VALUE IF NOT EXISTS 'rejected'")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
