"""create expense policy tables

Revision ID: bd698cc5de7d
Revises: fad536e1912c
Create Date: 2026-08-20 15:58:55.420351

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bd698cc5de7d"
down_revision: str | Sequence[str] | None = "fad536e1912c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_policies",
        sa.Column("policy_id", sa.String(length=32), nullable=False),
        sa.Column("policy_name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "uploaded", "processing", "published", "archived", name="expense_policy_status"
            ),
            server_default="uploaded",
            nullable=False,
        ),
        sa.Column("published_by", sa.String(length=320), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_name", "version", name="uq_expense_policy_name_version"),
    )
    op.create_index(
        op.f("ix_expense_policies_checksum"), "expense_policies", ["checksum"], unique=False
    )
    op.create_index(
        op.f("ix_expense_policies_document_id"), "expense_policies", ["document_id"], unique=True
    )
    op.create_index(
        op.f("ix_expense_policies_policy_id"), "expense_policies", ["policy_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_policies_policy_id"), table_name="expense_policies")
    op.drop_index(op.f("ix_expense_policies_document_id"), table_name="expense_policies")
    op.drop_index(op.f("ix_expense_policies_checksum"), table_name="expense_policies")
    op.drop_table("expense_policies")
    # ### end Alembic commands ###
