"""add storage key to documents

Revision ID: e368cc50222a
Revises: cc52f254a40a
Create Date: 2026-08-01 09:48:30.265540

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e368cc50222a"
down_revision: str | Sequence[str] | None = "cc52f254a40a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("storage_key", sa.String(length=500), nullable=True))
    op.execute(sa.text("UPDATE documents SET storage_key = '' WHERE storage_key IS NULL"))
    op.alter_column("documents", "storage_key", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "storage_key")
    # ### end Alembic commands ###
